#!/usr/bin/env bash

export QVDIT_AUTODL_ROOT="${QVDIT_AUTODL_ROOT:-/home/zhouchongtian/quantization}"
export TMPDIR="${TMPDIR:-$QVDIT_AUTODL_ROOT/cache/tmp}"
export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$QVDIT_AUTODL_ROOT/cache/pip}"
export HF_HOME="${HF_HOME:-$QVDIT_AUTODL_ROOT/cache/huggingface}"
export HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-$HF_HOME/hub}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$HF_HOME/transformers}"
export DIFFUSERS_CACHE="${DIFFUSERS_CACHE:-$HF_HOME/diffusers}"
export TORCH_HOME="${TORCH_HOME:-$QVDIT_AUTODL_ROOT/cache/torch}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$QVDIT_AUTODL_ROOT/cache}"

mkdir -p "$TMPDIR" "$PIP_CACHE_DIR" "$HUGGINGFACE_HUB_CACHE" \
  "$TRANSFORMERS_CACHE" "$DIFFUSERS_CACHE" "$TORCH_HOME"
